"""
pai_nosso_refatorado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/alanabdmorais/pai_nosso_refatorado/blob/main/pai_nosso_refatorado.ipynb

# 🎬 Pipeline Multilíngue — Orações com Legendas Morfológicas

**Estratégia de classificação intermediária:**
O Groq gera as classificações → você revisa com uma IA → pipeline continua com os JSONs corrigidos.

---

### Fluxo completo

| # | Fase | O que faz | Ação |
|---|------|-----------|------|
| 0 | Setup | Instala deps, monta Drive, importa módulos | Automático |
| Init | — | Cria config, groq e pipeline | Automático |
| B0 | YouTube | Baixa legendas de referência (opcional) | Manual |
| 1 | Áudio | Edge TTS → .wav no Drive | Automático |
| 2 | Whisper | Transcrição → SRT mestre (timestamps + segmentação) | Automático |
| 3 | Correção PT | Groq corrige o SRT | Automático |
| 4 | Traduções | Groq gera EN/ES/FR | Automático |
| **5A** | **Classificação** | **Groq classifica + gera pacote de revisão → pausa** | **Automático → pausa** |
| **5B** | **Revisão** | **Você corrige JSONs com IA externa** | **👤 Manual** |
| **5C** | **Recarregar** | **Pipeline carrega JSONs corrigidos** | **Automático** |
| 6 | Clipes | Baixa e corta vídeos do Pixabay | Automático |
| 7 | Vídeo base | Crédito + narração + trilha | Automático |
| 8 | Legendas ASS | Queima legendas coloridas no vídeo | Automático |

> **Retomar de uma fase:** `pipeline.run(from_phase='nome_da_fase')`
"""

# ╔══════════════════════════════════════════════════════════════════╗
# ║  🔧 LIMPAR PONTO DE MONTAGEM ANTES DO SETUP                     ║
# ╚══════════════════════════════════════════════════════════════════╝

import os
import shutil

# Forçar desmontagem
!fusermount -u /content/drive 2>/dev/null

# Limpar o diretório se tiver arquivos
if os.path.exists('/content/drive'):
    try:
        shutil.rmtree('/content/drive')
        print('✅ Diretório /content/drive removido')
    except:
        print('⚠️ Não foi possível remover, mas vamos tentar montar mesmo assim')

print('\n✅ Pronto para montar o Drive novamente')

# ╔══════════════════════════════════════════════════════════════════╗
# ║  CÉLULA 0 — Setup (rode uma vez por sessão)                    ║
# ╚══════════════════════════════════════════════════════════════════╝

# Sistema
!apt-get -qq -y install ffmpeg espeak-ng > /dev/null 2>&1
print('✅ ffmpeg + espeak-ng')

# Python
!pip install -q edge-tts openai-whisper openai pandas gdown yt-dlp nest_asyncio
print('✅ pacotes Python')

# Drive - FORÇAR REMONTAGEM
from google.colab import drive, userdata

# Tentar desmontar se já estiver montado
try:
    drive.flush_and_unmount()
    print('🔄 Desmontando Drive anterior...')
except:
    pass

# Montar com force_remount
drive.mount('/content/drive', force_remount=True)
print('✅ Drive montado')

# Copiar módulos do Drive para /content/pipeline
import shutil, os, sys, logging
from pathlib import Path

# CAMINHO PADRONIZADO: usando pasta modulos
PASTA_MODULOS = '/content/drive/MyDrive/pai_nosso_refatorado/pipeline/modulos'

# Fallback para o caminho antigo (caso não encontre)
if not os.path.exists(PASTA_MODULOS):
    PASTA_MODULOS_FALLBACK = '/content/drive/MyDrive/pipeline/modulos'
    if os.path.exists(PASTA_MODULOS_FALLBACK):
        PASTA_MODULOS = PASTA_MODULOS_FALLBACK
        print(f'⚠️ Usando fallback: {PASTA_MODULOS}')

DESTINO = '/content/pipeline'

if os.path.exists(PASTA_MODULOS):
    # Remove destino antigo se existir
    if os.path.exists(DESTINO):
        shutil.rmtree(DESTINO)

    shutil.copytree(PASTA_MODULOS, DESTINO, dirs_exist_ok=True)
    print(f'✅ Módulos copiados: {PASTA_MODULOS} → {DESTINO}')

    # Listar arquivos copiados
    print('\n📁 Arquivos copiados:')
    for py_file in sorted(Path(DESTINO).glob('*.py')):
        print(f'   📄 {py_file.name}')
else:
    print(f'❌ Pasta não encontrada: {PASTA_MODULOS}')
    print('   Verifique se os arquivos .py estão em:')
    print('   /content/drive/MyDrive/pai_nosso_refatorado/pipeline/modulos/')

if DESTINO not in sys.path:
    sys.path.insert(0, DESTINO)

# Logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s  %(name)-22s  %(levelname)s  %(message)s',
    datefmt='%H:%M:%S',
)

os.chdir('/content')
print('\n✅ Setup concluído!')

# ╔══════════════════════════════════════════════════════════════════╗
# ║  🚀 INICIALIZAÇÃO DO PIPELINE (com correção de path)            ║
# ╚══════════════════════════════════════════════════════════════════╝

import sys
import nest_asyncio
nest_asyncio.apply()

from pathlib import Path

# 🔧 CORREÇÃO: Adicionar o caminho dos módulos
caminho_modulos = '/content/pipeline'
if caminho_modulos not in sys.path:
    sys.path.insert(0, caminho_modulos)
    print(f"✅ Caminho adicionado: {caminho_modulos}")

# Verificar se os arquivos existem
from pathlib import Path
pipeline_dir = Path('/content/pipeline')
if pipeline_dir.exists():
    py_files = list(pipeline_dir.glob('*.py'))
    print(f"📁 {len(py_files)} arquivos encontrados em /content/pipeline/")
    for py in py_files[:5]:
        print(f"   📄 {py.name}")
else:
    print(f"❌ Pasta /content/pipeline/ não encontrada!")

# Importar módulos
from config import PipelineConfig
from groq_client import GroqClient
from video_pipeline import VideoPipeline
from checkpoint import Checkpoint
from google.colab import userdata

# Configuração
config = PipelineConfig(
    NOME_ORACAO = 'pai_nosso',
    # Para outra oração:
    # NOME_ORACAO  = 'ave_maria',
    # TEXTO_ORACAO = 'Ave Maria, cheia de graça...',
    # VOZ_EDGE     = 'pt-BR-FranciscaNeural',

    # Modo de vídeo:
    # False (padrão) = cores por palavra (classificação morfológica)
    # True           = cor sólida por idioma (pula classificação)
    VIDEO_SIMPLES_SEM_MORFOLOGIA = False,
)

# Cliente Groq
groq = GroqClient(
    api_key=userdata.get('GROQ_KEY'),
    nome_oracao=config.NOME_ORACAO
)

# Pipeline
pipeline = VideoPipeline(config, groq)

# Verificar checkpoint
cp = Checkpoint()
print("\n" + "="*60)
print("📋 CONFIGURAÇÃO DO PIPELINE")
print("="*60)
print(config.resumo())
print()
print(cp.resumo())
print(f"\n▶ Próxima fase: {cp.proxima_fase_pendente() or '(tudo concluído)'}")
print("="*60)

print("\n✅ Pipeline inicializado com sucesso!")

# ╔══════════════════════════════════════════════════════════════════╗
# ║  🧹 LIMPEZA SELETIVA (COM CAMINHOS CORRIGIDOS)                  ║
# ╚══════════════════════════════════════════════════════════════════╝

from pathlib import Path
import shutil
import sys
import os

# CAMINHOS CORRIGIDOS (apontando para o repositório consolidado)
BASE_DRIVE = Path('/content/drive/MyDrive/pai_nosso_refatorado/pipeline')
PASTA_BRUTOS = BASE_DRIVE / 'brutos'
PASTA_CORRECOES = BASE_DRIVE / 'correcoes'

def limpeza_seletiva():
    print("═" * 65)
    print("🧹 LIMPEZA SELETIVA")
    print("═" * 65)
    print("\nEscolha o que limpar (digite os números separados por vírgula)")
    print("Exemplo: 1,3,5")
    print("═" * 65)
    print("  1 - 🎵 Áudios (.wav, .mp3)")
    print("  2 - 📝 Legendas (.srt, .ass) [mantém yt_ref]")
    print("  3 - 🎬 Vídeos gerados (base, final, clipes)")
    print("  4 - 📊 JSONs BRUTOS (pasta brutos/ no Drive)")
    print("  5 - ✅ JSONs CORRIGIDOS (pasta correcoes/ no Drive)")
    print("  6 - 📌 Checkpoint (checkpoint.json)")
    print("  7 - 📁 Pastas temporárias (clipes_cortados, temp_raw)")
    print("  8 - 📦 Cache Python (módulos carregados)")
    print("  9 - 🗑️ Cache FASE 3 (fase3_cache.json)")
    print(" 10 - 🗑️ Cache Classificação (cache_classificacao/)")
    print(" 11 - 🔥 LIMPAR TUDO (exceto Drive)")
    print(" 12 - 🔥🔥 LIMPAR TUDO + DRIVE (TUDO)")
    print("  0 - Sair")
    print("═" * 65)

    opcoes = input("\nDigite sua escolha: ").strip()

    if opcoes == '0':
        print("Saindo...")
        return

    opcoes_lista = [int(x.strip()) for x in opcoes.split(',')]
    cont = 0

    # 1. Áudios
    if 1 in opcoes_lista or 11 in opcoes_lista or 12 in opcoes_lista:
        print("\n🎵 Removendo áudios...")
        for f in Path('.').glob('*_audio.wav'):
            f.unlink()
            cont += 1
            print(f"   🗑️ {f.name}")
        for f in Path('.').glob('*.mp3'):
            if 'musica' not in f.name:
                f.unlink()
                cont += 1
                print(f"   🗑️ {f.name}")

    # 2. Legendas
    if 2 in opcoes_lista or 11 in opcoes_lista or 12 in opcoes_lista:
        print("\n📝 Removendo legendas...")
        for f in Path('.').glob('*.srt'):
            if 'yt_ref' not in f.name:
                f.unlink()
                cont += 1
                print(f"   🗑️ {f.name}")
        for f in Path('.').glob('*.ass'):
            f.unlink()
            cont += 1
            print(f"   🗑️ {f.name}")

    # 3. Vídeos
    if 3 in opcoes_lista or 11 in opcoes_lista or 12 in opcoes_lista:
        print("\n🎬 Removendo vídeos...")
        patterns = ['*_base.mp4', '*_final.mp4', 'clipe_*.mp4', 'temp_*.mp4', 'video_*.mp4', 'raw_*.mp4']
        for pattern in patterns:
            for f in Path('.').glob(pattern):
                f.unlink()
                cont += 1
                print(f"   🗑️ {f.name}")

    # 4. JSONs BRUTOS (pasta brutos/ no Drive)
    if 4 in opcoes_lista or 12 in opcoes_lista:
        print("\n📊 Removendo JSONs BRUTOS...")
        if PASTA_BRUTOS.exists():
            for oracao_dir in PASTA_BRUTOS.iterdir():
                if oracao_dir.is_dir():
                    for f in oracao_dir.glob('classificacao_*.json'):
                        f.unlink()
                        cont += 1
                        print(f"   🗑️ brutos/{oracao_dir.name}/{f.name}")
        else:
            print("   ℹ️ Pasta brutos/ não encontrada")

    # 5. JSONs CORRIGIDOS (pasta correcoes/ no Drive)
    if 5 in opcoes_lista or 12 in opcoes_lista:
        print("\n✅ Removendo JSONs CORRIGIDOS...")
        if PASTA_CORRECOES.exists():
            for oracao_dir in PASTA_CORRECOES.iterdir():
                if oracao_dir.is_dir():
                    for f in oracao_dir.glob('classificacao_*.json'):
                        f.unlink()
                        cont += 1
                        print(f"   🗑️ correcoes/{oracao_dir.name}/{f.name}")
        else:
            print("   ℹ️ Pasta correcoes/ não encontrada")

    # 6. Checkpoint
    if 6 in opcoes_lista or 11 in opcoes_lista or 12 in opcoes_lista:
        print("\n📌 Removendo checkpoint...")
        cp = Path('checkpoint.json')
        if cp.exists():
            cp.unlink()
            cont += 1
            print("   🗑️ checkpoint.json")

    # 7. Pastas temporárias
    if 7 in opcoes_lista or 11 in opcoes_lista or 12 in opcoes_lista:
        print("\n📁 Removendo pastas temporárias...")
        pastas = ['clipes_cortados', 'clipes_prontos', 'temp_raw', '__pycache__']
        for pasta in pastas:
            p = Path(pasta)
            if p.exists():
                shutil.rmtree(p)
                cont += 1
                print(f"   🗑️ {pasta}/")

    # 8. Cache Python
    if 8 in opcoes_lista or 11 in opcoes_lista or 12 in opcoes_lista:
        print("\n📦 Limpando cache Python...")
        modulos = ['groq_client', 'video_pipeline', 'config', 'classification',
                   'checkpoint', 'drive_utils', 'ffmpeg_utils', 'srt_utils',
                   'models', 'constants', 'pipeline']
        for m in modulos:
            if m in sys.modules:
                del sys.modules[m]
                cont += 1
                print(f"   🗑️ {m}")

    # 9. Cache FASE 3
    if 9 in opcoes_lista or 11 in opcoes_lista or 12 in opcoes_lista:
        cache_fase3 = Path('/content/fase3_cache.json')
        if cache_fase3.exists():
            cache_fase3.unlink()
            cont += 1
            print("   🗑️ fase3_cache.json")

    # 10. Cache Classificação
    if 10 in opcoes_lista or 11 in opcoes_lista or 12 in opcoes_lista:
        cache_classif = Path('/content/cache_classificacao')
        if cache_classif.exists():
            shutil.rmtree(cache_classif)
            cont += 1
            print("   🗑️ cache_classificacao/")

    print("\n" + "═" * 65)
    print(f"✅ LIMPEZA CONCLUÍDA! {cont} item(ns) removido(s)")
    print("═" * 65)

# Executar
limpeza_seletiva()

"""
### 🔵 Célula B0 — Opcional: baixar legendas do YouTube
Execute **antes** das fases 1–8 para ter traduções mais fiéis. Se pular, o Groq traduz a partir do PT.
"""

# ╔══════════════════════════════════════════════════════════════════╗
# ║  CÉLULA B0 — Baixar legendas do YouTube                        ║
# ║  (BAIXA TAMBÉM A REFERÊNCIA PT para a FASE 3)                  ║
# ╚══════════════════════════════════════════════════════════════════╝

from pathlib import Path
import subprocess
import shutil
from drive_utils import DriveClient

cfg   = config
drive = DriveClient.get()

drive.download_se_ausente(cfg.ID_PASTA_COOKIES, cfg.NOME_COOKIES, Path(cfg.NOME_COOKIES))
cookies_flag = ['--cookies', cfg.NOME_COOKIES] if Path(cfg.NOME_COOKIES).exists() else []

print("═" * 60)
print("📺 BAIXANDO LEGENDAS DO YOUTUBE")
print("═" * 60)

# ── COLOQUE AS URLs DOS VÍDEOS COM LEGENDAS ABAIXO ────────────────────────────
URLS = {
    'pt': 'https://www.youtube.com/watch?v=p5Vg7Vn2KeM',
    'en': 'https://www.youtube.com/watch?v=p5Vg7Vn2KeM',
    'es': 'https://www.youtube.com/watch?v=p5Vg7Vn2KeM',
    'fr': 'https://www.youtube.com/watch?v=p5Vg7Vn2KeM',
}

for lang, url in URLS.items():
    nome_srt = cfg.nome_srt(lang)
    print(f'\n⬇️  Baixando {lang.upper()} de: {url[:50]}...')
    cmd = [
        'yt-dlp', '--write-sub', '--sub-lang', lang, '--write-auto-sub',
        '--skip-download', '--sub-format', 'srt', '--convert-subs', 'srt',
        '--output', f'{cfg.NOME_ORACAO}_{lang}', *cookies_flag, url
    ]
    resultado = subprocess.run(cmd, capture_output=True, text=True)
    encontrado = False
    for c in Path('.').glob(f'{cfg.NOME_ORACAO}_{lang}*.srt'):
        if c.name != nome_srt:
            c.rename(nome_srt)
        print(f'   ✅ {nome_srt} salvo')
        encontrado = True
        break
    if not encontrado:
        print(f'   ⚠️  Legenda {lang.upper()} não disponível nesse vídeo')

# Criar referência PT para a FASE 3
print("\n" + "═" * 60)
print("📝 PREPARANDO REFERÊNCIA PARA CORREÇÃO (FASE 3)")
print("═" * 60)
srt_pt   = Path(cfg.nome_srt('pt'))
ref_path = Path(f'{cfg.NOME_ORACAO}_yt_ref_pt.srt')
if srt_pt.exists():
    shutil.copy(srt_pt, ref_path)
    from srt_utils import ler_srt
    ref_legendas = ler_srt(ref_path)
    print(f'✅ Referência PT salva: {ref_path}  ({len(ref_legendas)} segmentos)')
    print(f'   Preview: {ref_legendas[0].texto[:80]}')
else:
    print(f'⚠️  SRT PT não encontrado. A FASE 3 corrigirá sem referência.')
print("═" * 60)

"""
### ▶ Fases 1–4 — Automáticas
"""

# ── FASE 1: Áudio com Edge TTS ───────────────────────────────────────────────
audio = pipeline.fase1_gerar_audio()
print(f'✅ {audio}  ({audio.stat().st_size/1024:.0f} KB)')



# ╔══════════════════════════════════════════════════════════════════╗
# ║  FASE 2 — Whisper (MESTRE de timestamps e segmentação)          ║
# ╚══════════════════════════════════════════════════════════════════╝

print('═' * 65)
print('🎙️ FASE 2 — WHISPER (mestre de timestamps e segmentação)')
print('   O Whisper segmenta por pausas naturais do áudio.')
print('   O texto será aprimorado na Fase 3 com referência do YouTube.')
print('═' * 65)

srt_bruto = pipeline.fase2_transcrever_whisper()

from srt_utils import ler_srt
legs_w = ler_srt(srt_bruto)
print(f'\n✅ Whisper: {len(legs_w)} segmentos')
for leg in legs_w:
    print(f'  [{leg.id:02d}]  {leg.inicio_str} → {leg.fim_str}  |  {leg.texto}')


# ╔══════════════════════════════════════════════════════════════════╗
# ║  🗑️ REMOVER CACHE CORROMPIDO                                   ║
# ╚══════════════════════════════════════════════════════════════════╝

from pathlib import Path

# Remover cache corrompido da FASE 3
cache_pt = Path('/content/pai_nosso_pt_corrigido.json')
if cache_pt.exists():
    tamanho = cache_pt.stat().st_size
    if tamanho == 0:
        cache_pt.unlink()
        print("✅ Cache corrompido (vazio) removido!")
    else:
        print(f"⚠️ Cache tem {tamanho} bytes - mantido")

# Remover cache de traduções se existir e estiver corrompido
cache_traducoes = Path('/content/pai_nosso_traducoes.json')
if cache_traducoes.exists():
    tamanho = cache_traducoes.stat().st_size
    if tamanho == 0:
        cache_traducoes.unlink()
        print("✅ Cache de traduções corrompido removido!")

print("\n✅ Pronto! Agora execute a FASE 3")

# ╔══════════════════════════════════════════════════════════════════╗
# ║  FASE 3 — PT definitivo (Whisper timestamps + YouTube texto)   ║
# ╚══════════════════════════════════════════════════════════════════╝

print('═' * 70)
print('📝 FASE 3 — SRT PT DEFINITIVO')
print('   Whisper = timestamps | YouTube = texto | Groq = limpeza leve')
print('═' * 70)

legendas = pipeline.fase3_corrigir_pt()

print(f'\n✅ FASE 3 CONCLUÍDA! | {len(legendas)} legendas')
print('\n📋 Resultado:')
for leg in legendas:
    print(f'  [{leg.id:02d}]  {leg.inicio_str} → {leg.fim_str}  |  {leg.texto}')


"""
▶ FASE 5A — Classificação Morfológica (Groq → Mistral) O que faz:

Classifica todos os idiomas via API (Groq ou Mistral)

Salva JSONs brutos localmente e faz backup no Drive (pasta brutos/)

⚠️ Após esta célula, execute a célula "PACOTE DE REVISÃO"
"""

# ╔══════════════════════════════════════════════════════════════════╗
# ║  FASE 5A — Classificação Morfológica (com delays otimizados)   ║
# ║  (Groq → Mistral) | Delay: 8s entre legendas | 15s entre idiomas║
# ╚══════════════════════════════════════════════════════════════════╝

from pathlib import Path
import time
import json
import re
from datetime import datetime
from google.colab import userdata
from openai import OpenAI
from srt_utils import ler_srt, salvar_srt
from models import Palavra, Legenda

print("═" * 70)
print("🤖 FASE 5A — CLASSIFICAÇÃO MORFOLÓGICA (OTIMIZADA)")
print("═" * 70)

# ═══════════════════════════════════════════════════════════════════
# CONFIGURAÇÕES (DELAYS REDUZIDOS)
# ═══════════════════════════════════════════════════════════════════

DELAY_ENTRE_LEGENDAS = 8       # 8 segundos entre cada legenda (antes 20)
DELAY_ENTRE_IDIOMAS = 15       # 15 segundos entre idiomas (antes 40)
DELAY_RATE_LIMIT = 60          # 60 segundos se bater rate limit (antes 90)

# Pastas de cache
CACHE_DIR = Path('/content/cache_classificacao')
CACHE_DIR.mkdir(exist_ok=True)

print(f"⏱️  Delay entre legendas: {DELAY_ENTRE_LEGENDAS}s")
print(f"⏱️  Delay entre idiomas: {DELAY_ENTRE_IDIOMAS}s")
print(f"⏱️  Delay rate limit: {DELAY_RATE_LIMIT}s")
print("═" * 70)

# ═══════════════════════════════════════════════════════════════════
# CONFIGURAÇÃO DAS APIS (Groq → Mistral)
# ═══════════════════════════════════════════════════════════════════

APIS_CONFIG = [
    {
        'nome': 'Groq',
        'secret_name': 'GROQ_KEY',
        'base_url': 'https://api.groq.com/openai/v1',
        'modelo': 'llama-3.3-70b-versatile',
    },
    {
        'nome': 'Mistral',
        'secret_name': 'MISTRAL_KEY',
        'base_url': 'https://api.mistral.ai/v1',
        'modelo': 'mistral-small-latest',
    },
]

def limpar_json(texto):
    """Tenta extrair e corrigir JSON mal formatado"""
    if not texto:
        return None

    # Tentar encontrar JSON entre chaves
    match = re.search(r'\{[^{}]*"palavras"\s*:\s*\[.*?\]\s*\}', texto, re.DOTALL)
    if not match:
        match = re.search(r'\{.*\}', texto, re.DOTALL)

    if not match:
        return None

    json_str = match.group()

    # Corrigir aspas simples para duplas
    json_str = re.sub(r"'", '"', json_str)

    # Remover trailing commas
    json_str = re.sub(r',\s*}', '}', json_str)
    json_str = re.sub(r',\s*]', ']', json_str)

    # Remover caracteres de controle
    json_str = re.sub(r'[\x00-\x1f\x7f-\x9f]', '', json_str)

    try:
        return json.loads(json_str)
    except:
        # Última tentativa: encontrar padrão de palavras
        palavras = re.findall(r'"texto"\s*:\s*"([^"]+)"\s*,\s*"classe"\s*:\s*"([^"]+)"', json_str)
        if palavras:
            return {"palavras": [{"texto": p[0], "classe": p[1]} for p in palavras]}

    return None

class APIClienteRotativo:
    def __init__(self, configs):
        self.apis = []
        for cfg in configs:
            try:
                api_key = userdata.get(cfg['secret_name'])
                if api_key:
                    self.apis.append({
                        'nome': cfg['nome'],
                        'client': OpenAI(api_key=api_key, base_url=cfg['base_url']),
                        'modelo': cfg['modelo']
                    })
                    print(f"   ✅ {cfg['nome']} - carregada")
                else:
                    print(f"   ⚠️ {cfg['nome']} - chave não encontrada")
            except Exception as e:
                print(f"   ❌ {cfg['nome']} - erro: {e}")

        self.indice = 0
        self.estatisticas = {api['nome']: {'tentativas': 0, 'sucessos': 0} for api in self.apis}
        print(f"\n📊 Total: {len(self.apis)} API(s) disponíveis")

    def classificar_legenda(self, texto, lang):
        """Classifica palavras de uma legenda usando JSON limpo"""
        prompt = f"""Idioma: {lang}
Texto: "{texto}"

Classifique cada palavra gramaticalmente. Use classes específicas como:
- substantivo_masculino_singular, substantivo_feminino_singular
- pronome_relativo, pronome_possessivo_singular, pronome_pessoal
- verbo_presente, verbo_passado, verbo_imperativo
- adjetivo_normal, advérbio_normal, preposicao, artigo_definido, conjuncao

REGRAS:
- 'que' em PT/ES/FR é pronome_relativo
- verbos no infinitivo são verbo_presente

Responda APENAS com JSON válido. Exemplo:
{{"palavras": [{{"texto": "Pai", "classe": "substantivo_masculino_singular"}}]}}"""

        for tentativa in range(len(self.apis) * 3):
            api = self.apis[self.indice]
            self.estatisticas[api['nome']]['tentativas'] += 1
            print(f"   🔄 Tentando: {api['nome']}...")

            try:
                messages = [
                    {"role": "system", "content": "Você é especialista em linguística. Responda apenas com JSON válido e bem formatado."},
                    {"role": "user", "content": prompt}
                ]

                resposta = api['client'].chat.completions.create(
                    model=api['modelo'],
                    messages=messages,
                    temperature=0.2,
                    max_tokens=800,
                )

                resultado = resposta.choices[0].message.content.strip()

                # Limpar e parsear JSON
                dados = limpar_json(resultado)
                if dados and 'palavras' in dados:
                    self.estatisticas[api['nome']]['sucessos'] += 1
                    print(f"   ✅ {api['nome']} respondeu!")
                    self.indice = 0

                    palavras = []
                    for p in dados['palavras']:
                        if p.get('texto'):
                            palavras.append(Palavra(
                                texto=p['texto'],
                                classe=p.get('classe', 'substantivo_masculino_singular')
                            ))
                    return palavras
                else:
                    print(f"   ⚠️ {api['nome']} JSON inválido, tentando novamente...")

            except Exception as e:
                erro = str(e).lower()
                if 'rate limit' in erro or '429' in erro:
                    print(f"   ⚠️ {api['nome']} RATE LIMIT! Aguardando {DELAY_RATE_LIMIT}s...")
                    time.sleep(DELAY_RATE_LIMIT)
                else:
                    print(f"   ⚠️ {api['nome']} erro: {erro[:50]}")

            self.indice = (self.indice + 1) % len(self.apis)
            time.sleep(5)

        print(f"   ❌ Todas as APIs falharam!")
        return [Palavra(texto=t, classe='substantivo_masculino_singular') for t in texto.split()]

    def resumo(self):
        print("\n📊 ESTATÍSTICAS DAS APIS:")
        print("═" * 50)
        for nome, stats in self.estatisticas.items():
            if stats['tentativas'] > 0:
                taxa = stats['sucessos'] / stats['tentativas'] * 100
                print(f"   {nome}: {stats['sucessos']}/{stats['tentativas']} ({taxa:.0f}%)")
            else:
                print(f"   {nome}: nenhuma tentativa")
        print("═" * 50)

# ═══════════════════════════════════════════════════════════════════
# FUNÇÕES DE CACHE
# ═══════════════════════════════════════════════════════════════════

def get_cache_path(lang, legenda_id):
    return CACHE_DIR / f'{config.NOME_ORACAO}_{lang}_leg{legenda_id}.json'

def carregar_do_cache(lang, legendas):
    cache_carregado = 0
    for leg in legendas:
        cache_path = get_cache_path(lang, leg.id)
        if cache_path.exists():
            try:
                with open(cache_path, 'r', encoding='utf-8') as f:
                    dados = json.load(f)
                leg.palavras = [Palavra(texto=p['texto'], classe=p['classe']) for p in dados]
                cache_carregado += 1
            except:
                pass
    return cache_carregado

def salvar_no_cache(lang, legenda):
    cache_path = get_cache_path(lang, legenda.id)
    dados = [{'texto': p.texto, 'classe': p.classe} for p in legenda.palavras]
    with open(cache_path, 'w', encoding='utf-8') as f:
        json.dump(dados, f, indent=2, ensure_ascii=False)

# ═══════════════════════════════════════════════════════════════════
# CARREGAR LEGENDAS (USANDO O SRT CORRIGIDO!)
# ═══════════════════════════════════════════════════════════════════

# ✅ usar o SRT corrigido
srt_corrigido = Path(config.NOME_SRT_PT)
if not srt_corrigido.exists():
    print(f"⚠️ SRT corrigido não encontrado: {srt_corrigido}")
    print("   Certifique-se de que a FASE 3 foi executada primeiro!")
else:
    legendas_pt = ler_srt(srt_corrigido)
    print(f"📖 Legendas PT carregadas do SRT CORRIGIDO: {len(legendas_pt)} segmentos")

    # Mostrar preview
    print("\n📝 Preview das legendas CORRIGIDAS:")
    for leg in legendas_pt[:3]:
        print(f"   #{leg.id:02d} {leg.texto[:60]}...")

# Carregar traduções
if not pipeline.legendas_idiomas:
    pipeline.legendas_idiomas = pipeline._carregar_todos_srts(legendas_pt)

print(f"\n📊 Total de legendas para classificar: {sum(len(pipeline.legendas_idiomas[lang]) for lang in config.IDIOMAS)}")
print("═" * 70)

# ═══════════════════════════════════════════════════════════════════
# CLASSIFICAR (COM CACHE)
# ═══════════════════════════════════════════════════════════════════

cliente = APIClienteRotativo(APIS_CONFIG)
inicio_total = datetime.now()

for i, lang in enumerate(config.IDIOMAS):
    print(f"\n{'='*60}")
    print(f"🔤 {lang.upper()} - {len(pipeline.legendas_idiomas[lang])} legendas")
    print(f"{'='*60}")

    # Carregar do cache primeiro
    cache_carregado = carregar_do_cache(lang, pipeline.legendas_idiomas[lang])
    if cache_carregado > 0:
        print(f"📁 Cache: {cache_carregado}/{len(pipeline.legendas_idiomas[lang])} legendas carregadas")

    for j, leg in enumerate(pipeline.legendas_idiomas[lang]):
        # Pular se já está no cache
        if get_cache_path(lang, leg.id).exists() and leg.palavras:
            print(f"   [{j+1}/{len(pipeline.legendas_idiomas[lang])}] ⏭️ Pulando (cache) - {leg.texto[:40]}...")
            continue

        print(f"\n   📝 [{j+1}/{len(pipeline.legendas_idiomas[lang])}] {leg.texto[:50]}...")

        inicio_leg = datetime.now()
        palavras = cliente.classificar_legenda(leg.texto, lang)
        tempo_leg = (datetime.now() - inicio_leg).seconds

        if palavras:
            leg.palavras = palavras
            salvar_no_cache(lang, leg)
            print(f"   ✅ Classificada em {tempo_leg}s ({len(palavras)} palavras)")
        else:
            print(f"   ❌ Falhou!")

        # DELAY entre legendas (REDUZIDO)
        if j < len(pipeline.legendas_idiomas[lang]) - 1:
            print(f"   ⏳ Aguardando {DELAY_ENTRE_LEGENDAS}s...")
            for s in range(DELAY_ENTRE_LEGENDAS, 0, -2):
                print(f"   ⏰ {s}s restantes...", end='\r')
                time.sleep(2)
            print()

    # DELAY entre idiomas (REDUZIDO)
    if i < len(config.IDIOMAS) - 1:
        print(f"\n⏳ Aguardando {DELAY_ENTRE_IDIOMAS}s antes do próximo idioma...")
        for s in range(DELAY_ENTRE_IDIOMAS, 0, -5):
            print(f"   ⏰ {s}s restantes...", end='\r')
            time.sleep(5)
        print()

# ═══════════════════════════════════════════════════════════════════
# SALVAR JSONs
# ═══════════════════════════════════════════════════════════════════

print("\n" + "═" * 70)
print("📦 SALVANDO CLASSIFICAÇÕES...")
print("═" * 70)

for lang in config.IDIOMAS:
    dados = {}
    for leg in pipeline.legendas_idiomas[lang]:
        dados[str(leg.id)] = {
            'inicio': leg.inicio_str,
            'fim': leg.fim_str,
            'texto_original': leg.texto,
            'palavras': [{'texto': p.texto, 'classe': p.classe} for p in leg.palavras]
        }

    json_path = Path(f'classificacao_{config.NOME_ORACAO}_{lang}.json')
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(dados, f, indent=2, ensure_ascii=False)
    print(f"   ✅ classificacao_{config.NOME_ORACAO}_{lang}.json")

tempo_total = (datetime.now() - inicio_total).seconds
print("\n" + "═" * 70)
print(f"✅ CLASSIFICAÇÃO CONCLUÍDA!")
print(f"   ⏱️  Tempo total: {tempo_total // 60}min {tempo_total % 60}s")
print("═" * 70)

cliente.resumo()

print("\n📦 Para gerar o pacote de revisão, execute:")
print("   pacote = pipeline._clf.exportar_pacote_revisao(pipeline.legendas_idiomas)")

"""
📦 PACOTE DE REVISÃO
O que faz:

Copia JSONs para a pasta de correções (correcoes/{oracao}/)

Cria prompt_revisao.md e relatorio_classificacoes.csv (se não existirem)

⚠️ Executar APÓS a FASE 5A
"""

# ╔══════════════════════════════════════════════════════════════════╗
# ║  📦 EXECUTAR PACOTE DE REVISÃO (cria guias + copia JSONs)       ║
# ║                                                                 ║
# ║  ✅ Cria prompt_revisao.md e relatorio_classificacoes.csv       ║
# ║  ✅ Copia JSONs para a pasta correta no Drive                   ║
# ║  ✅ Salva também na pasta local                                ║
# ╚══════════════════════════════════════════════════════════════════╝

print("═" * 65)
print("📦 EXECUTANDO PACOTE DE REVISÃO")
print("═" * 65)

# Executar o método que cria os guias e copia os JSONs
pasta_json = pipeline._clf.exportar_pacote_revisao(pipeline.legendas_idiomas)

print("\n" + "═" * 65)
print("✅ PACOTE DE REVISÃO EXECUTADO COM SUCESSO!")
print("═" * 65)

print(f"\n📁 JSONs salvos em: {pasta_json}")
print(f"📁 Guias salvos em: /content/drive/MyDrive/pai_nosso_refatorado/pipeline/correcoes/")

print("\n📄 ARQUIVOS CRIADOS:")
print("   📄 prompt_revisao.md")
print("   📄 relatorio_classificacoes.csv")

# Verificar se os arquivos foram criados (CAMINHO CORRIGIDO!)
from pathlib import Path
pasta_correcoes_root = Path('/content/drive/MyDrive/pai_nosso_refatorado/pipeline/correcoes')

print("\n🔍 VERIFICANDO ARQUIVOS:")
for arquivo in ['prompt_revisao.md', 'relatorio_classificacoes.csv']:
    caminho = pasta_correcoes_root / arquivo
    if caminho.exists():
        tamanho = caminho.stat().st_size / 1024
        print(f"   ✅ {arquivo} ({tamanho:.1f} KB)")
    else:
        print(f"   ❌ {arquivo} - erro na criação")

# ╔══════════════════════════════════════════════════════════════════╗
# ║  💾 DOWNLOAD AUTOMÁTICO (com caminhos corrigidos)               ║
# ╚══════════════════════════════════════════════════════════════════╝

from pathlib import Path
import shutil
import zipfile
from datetime import datetime
from google.colab import files

NOME_ORACAO = config.NOME_ORACAO

# CAMINHOS CORRETOS
pasta_correcoes_root = Path('/content/drive/MyDrive/pai_nosso_refatorado/pipeline/correcoes')
pasta_oracao = pasta_correcoes_root / NOME_ORACAO

print("═" * 65)
print("💾 PREPARANDO DOWNLOAD")
print("═" * 65)

# Criar pasta temporária
temp_dir = Path('/content/download_pacote')
temp_dir.mkdir(exist_ok=True)

# 1. Copiar guias
for guia in ['prompt_revisao.md', 'relatorio_classificacoes.csv']:
    src = pasta_correcoes_root / guia
    if src.exists():
        shutil.copy(src, temp_dir / guia)
        print(f"   ✅ {guia}")
    else:
        print(f"   ⚠️ {guia} - não encontrado")

# 2. Copiar JSONs (do local, que é o mais atual)
for lang in ['pt', 'en', 'es', 'fr']:
    src = Path(f'/content/classificacao_{NOME_ORACAO}_{lang}.json')
    if src.exists():
        shutil.copy(src, temp_dir / src.name)
        print(f"   ✅ {src.name}")
    else:
        print(f"   ❌ {src.name} - não encontrado")

# 3. Criar README
readme_content = f"""# PACOTE DE REVISÃO - {NOME_ORACAO.upper()}
## Data: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## INSTRUÇÕES:
1. Abra o prompt_revisao.md e copie o conteúdo
2. Cole numa IA (Claude, GPT, etc.)
3. Anexe os 4 JSONs
4. A IA retorna os JSONs corrigidos
5. Salve no: MyDrive/pai_nosso_refatorado/pipeline/correcoes/{NOME_ORACAO}/
6. Execute a FASE 5C
"""
(temp_dir / "LEIA-ME.txt").write_text(readme_content, encoding='utf-8')
print(f"   ✅ LEIA-ME.txt")

# 4. Criar ZIP
zip_path = Path('/content') / f'pacote_revisao_{NOME_ORACAO}.zip'
with zipfile.ZipFile(zip_path, 'w') as zipf:
    for arquivo in temp_dir.iterdir():
        zipf.write(arquivo, arquivo.name)

# 5. Limpar e baixar
shutil.rmtree(temp_dir)
files.download(str(zip_path))

print(f"\n✅ Download iniciado: pacote_revisao_{NOME_ORACAO}.zip")

"""
⏸️ FASE 5B — Revisão manual pela IA (você faz isso)
Após executar o PACOTE DE REVISÃO:

Abra o Google Drive → MyDrive/pipeline/correcoes/

Copie o conteúdo do arquivo prompt_revisao.md

Cole numa IA (Claude, GPT, etc.) junto com os 4 JSONs que estão na pasta da sua oração (ex: pai_nosso/)

A IA retorna os JSONs corrigidos

Salve os JSONs corrigidos na mesma pasta (substituindo os originais)

Execute a FASE 5C abaixo
"""

# ╔══════════════════════════════════════════════════════════════════╗
# ║  FASE 5C — Recarregar do Drive após revisão                    ║
# ║  Execute APÓS salvar os JSONs corrigidos no Drive              ║
# ╚══════════════════════════════════════════════════════════════════╝

from pathlib import Path

print("═" * 65)
print("📥 FASE 5C — RECARREGANDO CLASSIFICAÇÕES CORRIGIDAS")
print("═" * 65)

# CAMINHO CORRIGIDO (repositório consolidado)
pasta_correcoes = Path(f'/content/drive/MyDrive/pai_nosso_refatorado/pipeline/correcoes/{config.NOME_ORACAO}')

if not pasta_correcoes.exists():
    print(f"❌ Pasta não encontrada: {pasta_correcoes}")
    print("   Verifique se os JSONs corrigidos foram salvos no lugar certo")
    print("   Caminho esperado: MyDrive/pai_nosso_refatorado/pipeline/correcoes/pai_nosso/")
else:
    jsons_ok = []
    jsons_faltando = []
    for lang in config.IDIOMAS:
        p = pasta_correcoes / f'classificacao_{config.NOME_ORACAO}_{lang}.json'
        if p.exists():
            jsons_ok.append(lang.upper())
            print(f"   ✅ {p.name}")
        else:
            jsons_faltando.append(lang.upper())
            print(f"   ❌ {p.name}")

    if len(jsons_ok) == 4:
        print("\n✅ Todos os 4 JSONs encontrados! Carregando...")
        pipeline.legendas_idiomas = pipeline.fase5b_recarregar()

        print("\n📋 Preview das classificações:")
        print("─" * 55)
        for lang in config.IDIOMAS:
            legs = pipeline.legendas_idiomas.get(lang, [])
            if legs and legs[0].palavras:
                leg = legs[0]
                print(f'\n  {lang.upper()} — "{leg.texto[:50]}"')
                from constants import CORES_HTML
                for p in leg.palavras[:4]:
                    ok  = '✅' if p.classe in CORES_HTML else '❌'
                    print(f'    {ok} {p.texto:<18} {p.classe}')
                if len(leg.palavras) > 4:
                    print(f'       ... (+{len(leg.palavras)-4} palavras)')

        print("\n" + "═" * 65)
        print("🎬 Pronto — execute as Fases 6, 7 e 8")
        print("═" * 65)
    else:
        print(f"\n⚠️  Faltam: {', '.join(jsons_faltando)}")
        print(f"   Coloque os JSONs corrigidos em: {pasta_correcoes}")



"""
### ▶ Fases 6–8 — Vídeo final (rode após a Fase 5C)
"""

# ╔══════════════════════════════════════════════════╗
# ║  FASES 6, 7 e 8 — Vídeo final                 ║
# ╚══════════════════════════════════════════════════╝

video_final = pipeline.continuar()

if video_final:
    print(f'\n🎬 Vídeo final: {video_final}')
    print(f'   Tamanho: {video_final.stat().st_size / 1_048_576:.1f} MB')
    print(f'   Salvo no Drive: pasta Vídeos')



"""
### 🚀 RUN ALL — Pipeline completo com checkpoint

Use quando quiser rodar tudo de uma vez. O pipeline pausa automaticamente na Fase 5A
se houver classificações a revisar. Após a revisão, rode a célula da Fase 5C
e depois a célula das Fases 6–8.
"""

# ╔══════════════════════════════════════════════════╗
# ║  RUN ALL                                       ║
# ╚══════════════════════════════════════════════════╝
from video_pipeline import ClassificacaoPendenteError

resultado = pipeline.run(
    # from_phase='clipes_cortados'  # descomente para retomar de uma fase
)

if resultado is None:
    print('\n⏸️  Pipeline pausado na Fase 5A.')
    print('   Siga as instruções acima, depois execute a célula FASE 5C.')
else:
    print(f'\n🎉 Vídeo final: {resultado}')
    print(pipeline._cp.resumo())

# ╔══════════════════════════════════════════════════════════════════╗
# ║  🎬 VISUALIZAR VÍDEO FINAL NO COLAB                            ║
# ╚══════════════════════════════════════════════════════════════════╝

from pathlib import Path
from IPython.display import Video, display

# Caminho do vídeo final
video_path = Path(config.NOME_VIDEO_FINAL)

if video_path.exists():
    print("═" * 65)
    print("🎬 VÍDEO FINAL")
    print("═" * 65)
    print(f"\n📁 Arquivo: {video_path.name}")
    print(f"📏 Tamanho: {video_path.stat().st_size / 1_048_576:.1f} MB")
    print("\n🎬 Reproduzindo vídeo:\n")

    # Mostrar o vídeo
    display(Video(str(video_path), embed=True, width=800))

    print("\n" + "═" * 65)
    print("📂 Links:")
    print(f"   Local: /content/{video_path.name}")
    print(f"   Drive: https://drive.google.com/drive/folders/{config.ID_PASTA_VIDEOS}")
    print("═" * 65)
else:
    print(f"❌ Vídeo não encontrado: {video_path}")
    print("   Execute as FASES 6, 7 e 8 primeiro")

"""
### 🔧 Utilitários
"""

# ╔══════════════════════════════════════════════════╗
# ║  UTILITÁRIOS — descomente o que precisar       ║
# ╚══════════════════════════════════════════════════╝
from checkpoint import Checkpoint
cp = Checkpoint()
print(cp.resumo())
print()
pipeline._clf.imprimir_status()

# ── Checkpoint ────────────────────────────────────────────────────────────────
# cp.resetar_tudo()
# cp.reiniciar_de('classificacoes_feitas')

# ── Classificações ────────────────────────────────────────────────────────────
# pipeline._clf.imprimir_status()
# pipeline._clf.classificar_idioma(pipeline.legendas_idiomas['en'], 'en', forcar=True)

# Gerar pacote de revisão manualmente (sem reclassificar):
# pacote = pipeline._clf.exportar_pacote_revisao(pipeline.legendas_idiomas)
# print(f"📦 Pacote: {pacote}")

# Verificar classes inválidas:
# from constants import CORES_HTML
# for lang, legendas in pipeline.legendas_idiomas.items():
#     for leg in legendas:
#         for p in leg.palavras:
#             if p.classe not in CORES_HTML:
#                 print(f'  [{lang.upper()} leg.{leg.id}] "{p.texto}" → {p.classe} ❌')

"""
PONTOS A CORRIGIR NO PÓS MIGRAÇÃO:
## ✅ Concordo! Melhor sinalizar para a Claude refatorar depois.

### 📋 Resumo do que precisa ser ajustado:

| Problema | Local | Descrição |
|----------|-------|-----------|
| **1. JSONs salvos no lugar errado** | `classification.py` (método `exportar_pacote_revisao`) | Ainda salva em `pipeline/correcoes/` em vez de `pai_nosso_refatorado/pipeline/correcoes/` |
| **2. Guias salvos no lugar certo** | `classification.py` | Guias já vão para o lugar correto ✅ |
| **3. Verificação da célula** | Notebook (PACOTE REVISÃO) | Caminho de verificação está correto ✅ |
| **4. Segmentação PT** | FASE 3 | PT tem 12 legendas (deveria ser 11) |

### 📋 O que sinalizar para a Claude:

> **Problemas identificados após migração:**
>
> 1. O método `exportar_pacote_revisao` no `classification.py` ainda salva JSONs em `/content/drive/MyDrive/pipeline/correcoes/` em vez de `/content/drive/MyDrive/pai_nosso_refatorado/pipeline/correcoes/`
>
> 2. O PT está com 12 legendas (deveria ser 11, seguindo o YouTube)
>
> 3. A FASE 5A está funcionando (Mistral 100%) mas os delays podem ser otimizados
>
> **Solicitação:** Refatorar o `classification.py` para que o `exportar_pacote_revisao` use os caminhos corretos do repositório consolidado.




"""
